# Generated by Django 5.1.1 on 2024-09-20 23:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_modificacion', models.DateTimeField(default=None, null=True)),
                ('noticia', models.TextField(help_text='...ingrese aqui la noticia...')),
                ('imagen_portada', models.ImageField(default='../static/noticias/default.png', upload_to='noticias/')),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
    ]
