# Generated by Django 5.1.1 on 2024-09-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, default='static/default.png', null=True, upload_to='media/posts/'),
        ),
    ]
