# Generated by Django 4.2.16 on 2024-10-11 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='imagen',
            field=models.ImageField(blank=True, default='../static/default.png', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
